services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb+srv://lithira:2001@first.uyayw.mongodb.net/
      - JWT_SECRET=9177cfbb3a677a1305123a99297a000a2b1edb3a1a53a0866c0566ca09a3ececb7b04f31a53e21bf334adf58b5e24d58a7802b8e843306b3739749531c2f12a6
    depends_on:
      - mongo
    networks:
      - app-network

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb+srv://lithira:2001@first.uyayw.mongodb.net/
      - JWT_SECRET=9177cfbb3a677a1305123a99297a000a2b1edb3a1a53a0866c0566ca09a3ececb7b04f31a53e21bf334adf58b5e24d58a7802b8e843306b3739749531c2f12a6
      # Service URLs (use container names for Docker networking)
      - USER_SERVICE_URL=http://user-service:3001
      - NOTIFICATION_SERVICE_URL=http://notification-service:3005
      - PAYMENT_SERVICE_URL=http://payment-service:3007
      # Service tokens
      - NOTIFICATION_SERVICE_TOKEN=9177cfbb3a677a1305123a99297a000a2b1edb3a1a53a0866c0566ca09a3ececb7b04f31a53e21bf334adf58b5e24d58a7802b8e843306b3739749531c2f12a6
    depends_on:
      - mongo
      - user-service
      - notification-service
    networks:
      - app-network

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONGO_URI=mongodb+srv://lithira:2001@first.uyayw.mongodb.net/
      - JWT_SECRET=9177cfbb3a677a1305123a99297a000a2b1edb3a1a53a0866c0566ca09a3ececb7b04f31a53e21bf334adf58b5e24d58a7802b8e843306b3739749531c2f12a6
    depends_on:
      - mongo
    networks:
      - app-network

  delivery-service:
    build: ./delivery-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - MONGO_URI=mongodb+srv://lithira:2001@first.uyayw.mongodb.net/
      - JWT_SECRET=9177cfbb3a677a1305123a99297a000a2b1edb3a1a53a0866c0566ca09a3ececb7b04f31a53e21bf334adf58b5e24d58a7802b8e843306b3739749531c2f12a6
      # Service URLs (use container names for Docker networking)
      - ORDER_SERVICE_URL=http://order-service:3002
      - RESTAURANT_SERVICE_URL=http://restaurant-service:3003
      - USER_SERVICE_URL=http://user-service:3001
      - NOTIFICATION_SERVICE_URL=http://notification-service:3005
      # Service tokens
      - SERVICE_TOKEN=9177cfbb3a677a1305123a99297a000a2b1edb3a1a53a0866c0566ca09a3ececb7b04f31a53e21bf334adf58b5e24d58a7802b8e843306b3739749531c2f12a6
      - NOTIFICATION_SERVICE_TOKEN=9177cfbb3a677a1305123a99297a000a2b1edb3a1a53a0866c0566ca09a3ececb7b04f31a53e21bf334adf58b5e24d58a7802b8e843306b3739749531c2f12a6
    depends_on:
      - mongo
      - order-service
    networks:
      - app-network

  notification-service:
    build: ./notification-service
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - JWT_SECRET=9177cfbb3a677a1305123a99297a000a2b1edb3a1a53a0866c0566ca09a3ececb7b04f31a53e21bf334adf58b5e24d58a7802b8e843306b3739749531c2f12a6
      # Service tokens for authentication
      - NOTIFICATION_SERVICE_TOKEN=9177cfbb3a677a1305123a99297a000a2b1edb3a1a53a0866c0566ca09a3ececb7b04f31a53e21bf334adf58b5e24d58a7802b8e843306b3739749531c2f12a6
      # Email configuration
      - EMAIL_USER=foodyservicelk@gmail.com
      - EMAIL_PASS=ffamgvocrsczgvef
    depends_on:
      - mongo
    networks:
      - app-network

  admin-service:
    build: ./admin-service
    ports:
      - "3006:3006" 
    environment:
      - PORT=3006
      - MONGO_URI=mongodb+srv://lithira:2001@first.uyayw.mongodb.net/
      - JWT_SECRET=9177cfbb3a677a1305123a99297a000a2b1edb3a1a53a0866c0566ca09a3ececb7b04f31a53e21bf334adf58b5e24d58a7802b8e843306b3739749531c2f12a6
    depends_on:
       - mongo
    networks:
      - app-network

  payment-service:
    build: ./payment-service
    ports:
      - "3007:3007"
    environment:
      - PORT=3007
      - MONGO_URI=mongodb+srv://lithira:2001@first.uyayw.mongodb.net/
      - JWT_SECRET=9177cfbb3a677a1305123a99297a000a2b1edb3a1a53a0866c0566ca09a3ececb7b04f31a53e21bf334adf58b5e24d58a7802b8e843306b3739749531c2f12a6
      - STRIPE_SECRET_KEY=sk_test_51RIzREH4SbeQQ6uy6HGYLUZfaAoKEP1AfiepswYRAQloyAz8J0umEnm2A16C5uoyfermUPBSykTRowMofQ0wUlXg00QbxkF0Hq
      - ORDER_SERVICE_URL=http://order-service:3002
      - USER_SERVICE_URL=http://user-service:3001
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3001
      - REACT_APP_ORDER_API_URL=http://localhost:3002
      - REACT_APP_RESTAURANT_API_URL=http://localhost:3003
      - REACT_APP_DELIVERY_API_URL=http://localhost:3004
      - REACT_APP_NOTIFICATION_API_URL=http://localhost:3005
      - REACT_APP_ADMIN_API_URL=http://localhost:3006
      - REACT_APP_PAYMENT_API_URL=http://localhost:3007
    depends_on:
      - user-service
      - order-service
      - restaurant-service
      - delivery-service
      - notification-service
      - admin-service
      - payment-service
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge