apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: delivery-service:1.0
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              value: "3004"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: token
            - name: ORDER_SERVICE_URL
              value: "http://192.168.49.2:30002"
            - name: RESTAURANT_SERVICE_URL
              value: "http://192.168.49.2:30003"
            - name: USER_SERVICE_URL
              value: "http://192.168.49.2:30001"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://192.168.49.2:30005"
            - name: SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: token
            - name: NOTIFICATION_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: token
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  selector:
    app: delivery
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
      nodePort: 30004
  type: NodePort
