apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:1.0
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_BASE_URL
              value: "http://localhost:3001"
            - name: REACT_APP_ORDER_API_URL
              value: "http://localhost:3002"
            - name: REACT_APP_RESTAURANT_API_URL
              value: "http://localhost:3003"
            - name: REACT_APP_DELIVERY_API_URL
              value: "http://localhost:3004"
            - name: REACT_APP_NOTIFICATION_API_URL
              value: "http://localhost:3005"
            - name: REACT_APP_ADMIN_API_URL
              value: "http://localhost:3006"
            - name: REACT_APP_PAYMENT_API_URL
              value: "http://localhost:3007"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort
