apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-uri: bW9uZ29kYitzcnY6Ly9saXRoaXJhOjIwMDFAZmlyc3QudXlheXcubW9uZ29kYi5uZXQv  # Base64 encoded MongoDB URI
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  token: OTE3N2NmYmIzYTY3N2ExMzA1MTIzYTk5Mjk3YTAwMGEyYjFlZGIzYTFhNTNhMDg2NmMwNTY2Y2EwOWEzZWNlY2I3YjA0ZjMxYTUzZTIxYmYzMzRhZGY1OGI1ZTI0ZDU4YTc4MDJiOGU4NDMzMDZiMzczOTc0OTUzMWMyZjEyYTY=  # Base64 encoded JWT secret
---
apiVersion: v1
kind: Secret
metadata:
  name: email-secret
type: Opaque
data:
  email-user: Zm9vZHlzZXJ2aWNlbGtAZ21haWwuY29t  # Base64 encoded email user
  email-pass: ZmZhbWd2b2Nyc2N6Z3ZlZg==  # Base64 encoded email password
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  stripe-key: c2tfdGVzdF81MVJJelJFSDRTYmVRUTZ1eTZIR1lMVVpmYUFvS0VQMUFmaWVwc3dZUkFRbG95QXo4SjB1bUVubTJBMTZDNXVveWZlcm1VUEJTeWtUUm93TW9mUTB3VWxYZzAwUWJ4a0YwSHE=  # Base64 encoded Stripe key
